### PR TITLE
Disable logs for sync actions

### PR DESCRIPTION
**Pull request by tomasfejfar**
Unfortunately I don't really know how to test it properly... Fixes https://github.com/keboola/db-extractor-firebird/issues/11

### CODE REVIEW

**Review by pivnicek — APPROVED** [review]
Hmm, need the nullhandler class, and I'm making a test, mmt

**Comment by pivnicek** [comment]
Actually, if you want to test it you can send a `action: testConnection` via process execution of run.php and verify that the output has no logs

**Comment by pivnicek** [comment]
I'll rig up a quick test for this, just a sec

**Comment by pivnicek** [comment]
@tomasfejfar I fixed it a bit and added tests 🍻

**Comment by odinuv** [comment]
imho this should be backported to db-ex-common, if not there already

**Comment by pivnicek** [comment]
Not sure what you mean @odinuv , db-common does not have a run.php.  But I think v10 may handle it differently (ie within the Application, but I will need to verify that)

**Comment by tomasfejfar** [comment]
cc @Actimel

**Comment by odinuv** [comment]
@pivnicek exactly, it must be handled within db-exec-common application, otherwise we're gonna hit this error 8 more times
(this is exactly the code which should *not* be inside run.php in future (but in this PR it's ok, it's legacy)

**Comment by ujovlado** [comment]
Just passing by ... what's the point of that null handler? If application fails with proper exit code (even for sync action), it is correctly handled by docker runner. Or not? I simply cannot remember fixing this in any of components.

**Comment by pivnicek** [comment]
ah, gotcha, yes, 10 should handle that differently  (fwiw all db-ex run.php have this, this one is really old but I'm still surprised it wasn't there)

btw, I moved the 2 tests into different testsuites because if you try to create ssh tunnel in 2 different test files in the same suite it breaks  (In other exes I've gotten around this by moving all ssh tests into a single file)

**Comment by pivnicek** [comment]
@ujovlado in this case, when connecting to SSH tunnel the extractor logs a message.  This message is sent to stdout if the NullHandler is not there, and that means that the stdout is not valid json.

**Comment by odinuv** [comment]
@ujovlado in sync action, the application mustn't output anything but the JSON https://developers.keboola.com/extend/common-interface/actions/#return-values

**Comment by odinuv** [comment]
it might be worth implementing this to php-component, but there is no support for sync actions there so far

**Comment by ujovlado** [comment]
> @ujovlado in sync action, the application mustn't output anything but the JSON https://developers.keboola.com/extend/common-interface/actions/#return-values

Yes I remember that, but only for actions ending with "success". Ok then, I'll try to "break" (later) one of the extractors where I'm not using NullHandler and using SSH. Thx.

**Comment by tomasfejfar** [comment]
Now that I saw some of the sync actions I'm confident I can add the support to php-component. I  didn't understand what they do and how they work before. 

https://github.com/keboola/php-component/issues/45

**Comment by odinuv** [comment]
ok, then so we should try to add this to php-component (though i still have no idea how, but i trust @tomasfejfar :D) before db-ex-common v10 is final (as it will remove a significant piece of code from there)

**Comment by Actimel** [comment]
It can be done almost immediately by adding it here https://github.com/keboola/db-extractor-common/blob/0b5db25d99a5c34cc237e934d37fe51bf3c01f1a/src/Keboola/DbExtractor/Extractor/BaseExtractor.php#L63

I'm not really sure if php-component should care about that. It's more extractor's thing.

**Comment by pivnicek** [comment]
> I'm not really sure if php-component should care about that. It's more extractor's thing.

I think I disagree with that.  Synch actions are generic and can be literally anything and they all require clean output.  The only action that doesn't is run (until more async actions get introduced)

**Comment by Actimel** [comment]
Ok then. Maybe we should consider using `info()` here https://github.com/keboola/db-extractor-common/blob/master/src/Keboola/DbExtractor/Extractor/Extractor.php#L108 and use `debug()` instead. That will solve this issue.

But for future purposes we should implement that NullPointer logger for `info()` in php-component as well.

**Comment by Actimel** [comment]
That NullHandler will not solve this completely. We should implement json response for sync actions. E.g. when you try to run undefined action you want to get response like this `{"error": "Undefined action XY"}`

When we mute Logger only, on failure whole response will be empty.

**Comment by ujovlado** [comment]
I thought that we only need valid JSONs on  "success" actions. So if I call unknown action, is it ok to throw exception and return text response. Or not?

**Comment by pivnicek** [comment]
[just an idea] I would vote for 2 loggers, a synch action logger that mutes `stdout` messages and allows `stderr` messages, and an async action logger which is like we have now.  The appropriate logger can be passed to the application in accordance with action type.

**Comment by pivnicek** [comment]
Regardless, I think this bug is fixed adequately by this PR.  It uses the same logic here as all other live db-extractors.  Can we merge this?

**Comment by odinuv** [comment]
@Actimel not really, rtfm https://developers.keboola.com/extend/common-interface/actions/#handling-user-and-application-errors

**Comment by odinuv** [comment]
@pivnicek - https://github.com/keboola/db-extractor-firebird/pull/12#issuecomment-428573078 - sync actions have no jobs, so we have no proper way of displaying the events - they're just dangling events. So neither stdout nor stderr will be logged into storage in https://github.com/keboola/runner-sync-api
. stderr should go to PT though, so it might be useful for debugging

**Review by MiroCillik — APPROVED** [review]
lgtm

**Comment by pivnicek** [comment]
ok, I'm releasing this:)

**Pull request merged**
