### PR TITLE
ssh tunnel support

### LINKED ISSUE #9: SSH Tunnel support

### PR DESCRIPTION
**Pull request by pivnicek**
fixes #9

### CODE REVIEW

**Comment by pivnicek** [comment]
There's a problem that this connector doesn't separate dbname from host so it'll need to be parsed out (hopefully)

**Comment by ondrejhlavacek** [comment]
@pivnicek why am i requested for PR here? because I was on zendesk when this popped up or is there some other relation I cannot remember now? :-)

**Comment by pivnicek** [comment]
@ondrejhlavacek yeah, mainly because erik and miro are away and I wanted to push it a bit.  but if we can wait then it's fine

**Comment by ondrejhlavacek** [comment]
@pivnicek oh, i see! i'll add it to the heap of PR reviews i have planned for this week. but it won't be tomorrow, the heap is big :-(

**Comment by pivnicek** [comment]
@ondrejhlavacek  ah, nvm, I see that @MiroCillik is back tomorrow.  sorry for the distraction!

**Review by MiroCillik — APPROVED** [review]
LGTM

**Pull request merged**
